# Generated by Django 3.1.7 on 2021-03-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinkpiece',
            name='slug',
        ),
    ]
